import { beforeEach, afterEach, expect, it } from 'vitest';
import { mount } from '@vue/test-utils';
import router from '../../router';
import SidebarNav from '../../components/navigation/SidebarNav.vue';
import ErpLayout from '../../layouts/ErpLayout.vue';
import { saveCurrentUser, clearCurrentUser } from '../../services/authSession';
import { ACCESS_TOKEN_STORAGE_KEY } from '../../types/auth';
beforeEach(() => { localStorage.clear(); clearCurrentUser(); });
afterEach(clearCurrentUser);
it('protects the shipping route and exposes its menu only with view permission', async () => {
  localStorage.setItem(ACCESS_TOKEN_STORAGE_KEY,'test');
  saveCurrentUser({accessToken:'test',mobile:null,roles:[],permissions:['dashboard:view'],loginMethod:'feishu'});
  await router.push('/shipping/list');
  expect(router.currentRoute.value.name).toBe('workbench');
  const hidden = mount(SidebarNav,{global:{plugins:[router]}});
  expect(hidden.text()).not.toContain('发货管理');
  hidden.unmount();
  saveCurrentUser({accessToken:'test',mobile:null,roles:[],permissions:['shipping:view'],loginMethod:'feishu'});
  await router.push('/shipping/list');
  expect(router.currentRoute.value.name).toBe('shipping-list');
  const visible = mount(SidebarNav,{global:{plugins:[router]}});
  expect(visible.text()).toContain('发货管理');
  expect(visible.find('a[href="/shipping/list"]').exists()).toBe(true);
  visible.unmount();
  const layout = mount(ErpLayout,{global:{plugins:[router],stubs:{RouterView:true}}});
  await router.push('/shipping/list');
  expect(layout.get('[data-testid="breadcrumb-current"]').text()).toBe('发货列表');
  layout.unmount();
});
