<script setup lang="ts">
import OrganizationPagination from '../../organization/components/OrganizationPagination.vue';
import type { RoleMemberPage } from '../types';

const props = defineProps<{ page: RoleMemberPage; canManage: boolean; selectedIds: number[]; keyword?: string; departmentId?: number | null; departments?: { id: number; name: string }[] }>();
const emit = defineEmits<{ page: [page: number]; 'page-size': [pageSize: number]; keyword: [keyword: string]; department: [departmentId: number | null]; 'update:selectedIds': [ids: number[]]; add: []; remove: [ids: number[]]; clear: [] }>();
function setSelected(employeeId: number, checked: boolean) { const next = new Set(props.selectedIds); checked ? next.add(employeeId) : next.delete(employeeId); emit('update:selectedIds', [...next]); }
function dataScopeLabel(scope: string | null) { return ({ company: '全公司', 'department-and-descendants': '本部门及下级', department: '本部门', self: '仅本人' } as Record<string, string>)[scope ?? ''] ?? '—'; }
</script>

<template>
  <section class="flex min-h-0 flex-1 flex-col" data-testid="role-members-panel">
    <header class="flex flex-wrap items-center gap-3 pb-4"><input data-testid="member-keyword" aria-label="搜索成员" type="search" :value="keyword ?? ''" class="h-9 rounded-[6px] border border-slate-200 px-3 text-sm" placeholder="搜索姓名、手机号、工号" @input="emit('keyword', ($event.target as HTMLInputElement).value)" /><select data-testid="member-department" aria-label="筛选部门" :value="departmentId ?? ''" class="h-9 rounded-[6px] border border-slate-200 px-3 text-sm" @change="emit('department', ($event.target as HTMLSelectElement).value ? Number(($event.target as HTMLSelectElement).value) : null)"><option value="">全部部门</option><option v-for="department in departments ?? []" :key="department.id" :value="department.id">{{ department.name }}</option></select><button data-testid="member-add" type="button" class="ml-auto text-sm text-[#536dff] disabled:opacity-50" :disabled="!canManage" @click="emit('add')">添加成员</button><button data-testid="member-remove-selected" type="button" class="text-sm text-rose-600 disabled:opacity-50" :disabled="!canManage || selectedIds.length === 0" @click="emit('remove', selectedIds)">批量移除</button></header>
    <div class="min-h-0 flex-1 overflow-auto border-y border-slate-200"><table class="w-full min-w-[760px] text-sm"><thead class="text-left text-xs text-slate-500"><tr><th class="p-3">选择</th><th>员工信息</th><th>部门 / 岗位</th><th>用工类型</th><th>其他角色</th><th><span>最终数据范围</span><button data-testid="member-scope-help" type="button" class="ml-1 text-slate-400 underline decoration-dotted" aria-label="最终数据范围按最宽的启用角色范围生效。" aria-describedby="member-scope-help-text" title="最终数据范围按最宽的启用角色范围生效。">?</button><span id="member-scope-help-text" role="tooltip" class="sr-only">最终数据范围按最宽的启用角色范围生效。</span></th><th>操作</th></tr></thead><tbody><tr v-for="member in page.records" :key="member.employeeId" class="border-t border-slate-200 text-[#25314d]"><td class="p-3"><input :data-testid="`member-select-${member.employeeId}`" :aria-label="`选择成员 ${member.employeeName}`" type="checkbox" :checked="selectedIds.includes(member.employeeId)" :disabled="!canManage || Boolean(member.lockedReason)" @change="setSelected(member.employeeId, ($event.target as HTMLInputElement).checked)" /></td><td><div>{{ member.employeeName }}</div><div class="text-xs text-slate-400">{{ member.employeeNo }} · {{ member.mobile }}</div></td><td>{{ member.departmentName }} / {{ member.positionName }}</td><td>{{ member.employmentType === 'formal' ? '正式' : '临时' }}</td><td>{{ member.otherRoleNames.join('、') || '—' }}</td><td>{{ dataScopeLabel(member.finalDataScope) }}</td><td><span v-if="member.lockedReason" class="text-xs text-slate-400">不可移除 · {{ member.lockedReason }}</span><button v-else type="button" class="text-[#536dff] disabled:opacity-50" :disabled="!canManage" @click="emit('remove', [member.employeeId])">移除</button></td></tr><tr v-if="page.records.length === 0"><td colspan="7" class="p-10 text-center text-sm text-slate-400">暂无授权成员 <button data-testid="member-clear-filters" type="button" class="text-[#536dff]" @click="emit('clear')">清空筛选</button></td></tr></tbody></table></div>
    <OrganizationPagination class="sticky bottom-0" :page="page.page" :page-size="page.pageSize" :total="page.total" test-id-prefix="member-" @page="emit('page', $event)" @page-size="emit('page-size', $event)" />
  </section>
</template>
