<script setup lang="ts">
import { ArrowDownRight, ArrowUpRight, PackageCheck, ShoppingCart, WalletCards, Warehouse } from 'lucide-vue-next';

const realtimeStats = [{ label: '待付款', value: '0' }, { label: '待发货', value: '0' }, { label: '待售后', value: '0' }, { label: '待评价', value: '0' }];
const summary = [{ label: '累计顾客数', value: '0', trend: 'up' }, { label: '累计商家数', value: '0', trend: 'down' }, { label: '访问次数(PV)', value: '0', trend: 'up' }, { label: '访问人数(UV)', value: '0', trend: 'down' }];
</script>

<template>
  <section class="mx-auto max-w-[1440px] space-y-6">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm font-bold text-slate-400">Dashboards</p><h1 class="mt-1 text-2xl font-black">工作台</h1></div><span class="rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-400 shadow-sm">今日经营概览</span></div>
    <section class="overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-[0_14px_40px_rgba(31,45,74,0.04)]"><div class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 px-6 py-5"><div><h2 class="text-xl font-black">实时交易</h2><p class="mt-1 text-sm font-medium text-slate-400">订单与库存处理状态</p></div><ShoppingCart class="h-6 w-6 text-[#536dff]" /></div><div class="grid grid-cols-2 divide-x divide-y divide-slate-100 md:grid-cols-4 md:divide-y-0"><article v-for="item in realtimeStats" :key="item.label" class="p-5"><p class="text-sm font-bold text-slate-400">{{ item.label }}</p><p class="mt-3 text-3xl font-black">{{ item.value }}</p></article></div></section>
    <div class="grid gap-6 xl:grid-cols-[1.5fr_0.9fr]"><section class="rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_14px_40px_rgba(31,45,74,0.04)]"><div class="flex items-center justify-between"><h2 class="text-xl font-black">运营数据</h2><span class="text-sm font-bold text-slate-400">本月</span></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><article v-for="item in summary" :key="item.label" class="rounded-2xl border border-slate-100 p-5"><div class="flex items-center justify-between"><span class="text-sm font-bold text-slate-400">{{ item.label }}</span><ArrowUpRight v-if="item.trend === 'up'" class="h-4 w-4 text-emerald-500" /><ArrowDownRight v-else class="h-4 w-4 text-rose-500" /></div><p class="mt-4 text-3xl font-black">{{ item.value }}</p></article></div></section><aside class="rounded-[22px] border border-slate-200 bg-white p-6 shadow-[0_14px_40px_rgba(31,45,74,0.04)]"><h2 class="text-xl font-black">快捷入口</h2><div class="mt-5 space-y-3"><RouterLink :to="{ name: 'sales-orders' }" class="flex items-center gap-3 rounded-xl border border-slate-100 p-4 font-bold hover:bg-slate-50"><WalletCards class="h-5 w-5 text-[#536dff]" />销售单据</RouterLink><RouterLink :to="{ name: 'products' }" class="flex items-center gap-3 rounded-xl border border-slate-100 p-4 font-bold hover:bg-slate-50"><PackageCheck class="h-5 w-5 text-[#36bee3]" />产品资料</RouterLink><RouterLink :to="{ name: 'inventory-balances' }" class="flex items-center gap-3 rounded-xl border border-slate-100 p-4 font-bold hover:bg-slate-50"><Warehouse class="h-5 w-5 text-[#7b45f5]" />库存管理</RouterLink></div></aside></div>
  </section>
</template>
